baseURL = "https://example.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hallo"
theme = "hallo-hugo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Vajresh Balaji"
    
[params.colors]
    background = "#81c6ff"
    foreground = "#edf7ff"
    hover = "#ffba82"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:contact@vajresh.in"
    
    [[params.links]]
        iconset = "fas"
        icon = "pencil-alt"
        title = "Blog"
        url = "https://bvajresh.substack.com"
    
    [[params.links]]
        iconorigin = "ai"
        iconset = "ai"
        icon = "google-scholar"
        title = "Google Scholar"
        url = "https://scholar.google.com/citations?hl=en&user=7Llyz7QAAAAJ"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/bvajresh"
    
    [[params.links]]
        icon = "linkedin-in"
        title = "Linkedin"
        url = "https://linkedin.com/in/bvajresh"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/bvajresh"
    
    
